server:
  port: 8081

spring:
  application:
    name: producer-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/{테이블명}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {아이디}
    password: {비밀번호}
